# Generated by Django 5.2.4 on 2025-07-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(default='Topfiyt', max_length=200)),
                ('hero_title', models.CharField(default='Dizi ve film dünyasının buluşma noktası', max_length=300)),
                ('hero_description', models.TextField(default='Oyuncular, yapımcılar ve ekipler için profesyonel platform.')),
                ('feature1_title', models.CharField(default='Oyuncu Bulma', max_length=100)),
                ('feature1_desc', models.TextField(default='Yeni projeler için yetenekli oyuncuları keşfedin.')),
                ('feature2_title', models.CharField(default='Set ve Ekipman Kiralama', max_length=100)),
                ('feature2_desc', models.TextField(default='Film çekimleri için gerekli tüm ekipmanları kolayca bulun.')),
                ('feature3_title', models.CharField(default='Teknik Ekip Yönetimi', max_length=100)),
                ('feature3_desc', models.TextField(default='Profesyonel teknik ekiplerle projelerinizi yönetin.')),
                ('footer_text', models.TextField(default='© 2025 Topfiyt. Tüm hakları saklıdır.')),
                ('footer_contact', models.CharField(default='info@topfiyt.com | +90 555 123 45 67', max_length=200)),
            ],
        ),
    ]
