# Generated by Django 5.2.4 on 2025-07-10 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_slideritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideritem',
            name='landing_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='api.landingpagecontent'),
            preserve_default=False,
        ),
    ]
