# Generated by Django 5.2.4 on 2025-07-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_slideritem_landing_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecontent',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
