# Generated by Django 5.2.4 on 2025-07-10 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_landingpagecontent_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='feature1_desc',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='feature1_title',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='feature2_desc',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='feature2_title',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='feature3_desc',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='feature3_title',
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api.landingpagecontent')),
            ],
        ),
    ]
