# Generated by Django 5.1.4 on 2025-07-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_whatistopfiytitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopfiytForWhoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Sıralama için')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
