# Generated by Django 5.1.4 on 2025-07-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_topfiytforwhoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='topfiytforwhoitem',
            name='category',
            field=models.CharField(choices=[('bireysel', 'Bireysel'), ('kurumsal', 'Kurumsal')], default='bireysel', max_length=10),
        ),
    ]
