# Generated by Django 5.1.4 on 2025-07-14 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_topfiytforwhoitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('column1_title', models.CharField(max_length=200)),
                ('column2_title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.IntegerField(choices=[(1, 'Column 1'), (2, 'Column 2')])),
                ('text', models.CharField(max_length=255)),
                ('is_main', models.BooleanField(default=False)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.footer')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
