# Generated by Django 5.1.4 on 2025-07-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_footer_footeritem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='footer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='footer_logos/'),
        ),
    ]
