# Generated by Django 5.1.4 on 2025-07-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_footer_logo_url_footer_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footeritem',
            name='is_main',
        ),
        migrations.AlterField(
            model_name='footer',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='footer',
            name='column1_title',
            field=models.CharField(default='Topfiyt', max_length=200),
        ),
        migrations.AlterField(
            model_name='footer',
            name='column2_title',
            field=models.CharField(default='İletişim', max_length=200),
        ),
        migrations.AlterField(
            model_name='footer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='footer',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='footeritem',
            name='column',
            field=models.IntegerField(choices=[(1, 'Sütun 1'), (2, 'Sütun 2')]),
        ),
    ]
