# Generated by Django 5.1.4 on 2025-07-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_footeritem_is_main_alter_footer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footeritem',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
