# Generated by Django 5.1.4 on 2025-07-16 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_footeritem_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footeritem',
            name='footer',
        ),
        migrations.DeleteModel(
            name='Footer',
        ),
        migrations.DeleteModel(
            name='FooterItem',
        ),
    ]
