# Generated by Django 5.1.4 on 2025-07-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='topfiyt_features_content',
            field=models.TextField(default='Profil sayfaları, mesajlaşma, küçük ilanlar, mekan ilanları ve daha fazlası.'),
        ),
        migrations.AddField(
            model_name='footer',
            name='topfiyt_features_title',
            field=models.CharField(default='TopFiyt’te Neler Var?', max_length=255),
        ),
        migrations.AddField(
            model_name='footer',
            name='topfiyt_for_who_content',
            field=models.TextField(default='Bireyler, firmalar, prodüksiyon ekipleri ve daha fazlası için içerikler.'),
        ),
        migrations.AddField(
            model_name='footer',
            name='topfiyt_for_who_title',
            field=models.CharField(default='TopFiyt Kimler İçin', max_length=255),
        ),
    ]
