# Generated by Django 5.1.4 on 2025-07-16 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_footer_topfiyt_features_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='topfiyt_features_content',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='topfiyt_for_who_content',
        ),
        migrations.CreateModel(
            name='FooterFeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_items', to='api.footer')),
            ],
        ),
        migrations.CreateModel(
            name='FooterForWhoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_who_items', to='api.footer')),
            ],
        ),
    ]
